import type { Wrestler } from "./types";

export const AwayRoster: Wrestler[] = [
  { "firstName": "Mikey", "lastName": "Bartush", "primaryWeightClass": 184, "secondaryWeightClass": undefined, "year": 4, "isRedshirt": false },
  { "firstName": "Dillon", "lastName": "Bechtold", "primaryWeightClass": 197, "secondaryWeightClass": undefined, "year": 2, "isRedshirt": false },
  { "firstName": "Owen", "lastName": "Bell", "primaryWeightClass": 125, "secondaryWeightClass": undefined, "year": 3, "isRedshirt": false },
  { "firstName": "Tyler", "lastName": "Bienus", "primaryWeightClass": 184, "secondaryWeightClass": undefined, "year": 2, "isRedshirt": false },
  { "firstName": "Braden", "lastName": "Bower", "primaryWeightClass": 141, "secondaryWeightClass": 149, "year": 4, "isRedshirt": false },
  { "firstName": "Riley", "lastName": "Bower", "primaryWeightClass": 149, "secondaryWeightClass": 157, "year": 4, "isRedshirt": false },
  { "firstName": "Dylan", "lastName": "Chappell", "primaryWeightClass": 141, "secondaryWeightClass": undefined, "year": 5, "isRedshirt": false },
  { "firstName": "Vinnie", "lastName": "D'Alessandro", "primaryWeightClass": 141, "secondaryWeightClass": undefined, "year": 2, "isRedshirt": false },
  { "firstName": "Kade", "lastName": "Davidheiser", "primaryWeightClass": 125, "secondaryWeightClass": undefined, "year": 3, "isRedshirt": false },
  { "firstName": "Aiden", "lastName": "Davis", "primaryWeightClass": 149, "secondaryWeightClass": undefined, "year": 3, "isRedshirt": false },
  { "firstName": "Dante", "lastName": "Donaldson", "primaryWeightClass": 285, "secondaryWeightClass": undefined, "year": 1, "isRedshirt": false },
  { "firstName": "Riley", "lastName": "Godek", "primaryWeightClass": 285, "secondaryWeightClass": undefined, "year": 4, "isRedshirt": false },
  { "firstName": "Oliver", "lastName": "Graham", "primaryWeightClass": 149, "secondaryWeightClass": undefined, "year": 3, "isRedshirt": false },
  { "firstName": "Will", "lastName": "Greenberg", "primaryWeightClass": 285, "secondaryWeightClass": undefined, "year": 1, "isRedshirt": false },
  { "firstName": "Lucas", "lastName": "Lawler", "primaryWeightClass": 285, "secondaryWeightClass": undefined, "year": 1, "isRedshirt": false },
  { "firstName": "Ethan", "lastName": "Lebin", "primaryWeightClass": 141, "secondaryWeightClass": undefined, "year": 3, "isRedshirt": false },
  { "firstName": "Stephen", "lastName": "Lukas", "primaryWeightClass": 141, "secondaryWeightClass": undefined, "year": 4, "isRedshirt": false },
  { "firstName": "Bryce", "lastName": "Manera", "primaryWeightClass": 133, "secondaryWeightClass": undefined, "year": 1, "isRedshirt": false },
  { "firstName": "Logan", "lastName": "McDermid", "primaryWeightClass": 125, "secondaryWeightClass": 133, "year": 1, "isRedshirt": false },
  { "firstName": "Shane", "lastName": "McFillin", "primaryWeightClass": 165, "secondaryWeightClass": undefined, "year": 1, "isRedshirt": false },
  { "firstName": "Noah", "lastName": "Mulvaney", "primaryWeightClass": 165, "secondaryWeightClass": undefined, "year": 3, "isRedshirt": false },
  { "firstName": "Chris", "lastName": "Nucifora", "primaryWeightClass": 125, "secondaryWeightClass": undefined, "year": 2, "isRedshirt": false },
  { "firstName": "Meyer", "lastName": "Rosen", "primaryWeightClass": 125, "secondaryWeightClass": undefined, "year": 3, "isRedshirt": false },
  { "firstName": "Kaden", "lastName": "Schaefer", "primaryWeightClass": 149, "secondaryWeightClass": undefined, "year": 2, "isRedshirt": false },
  { "firstName": "Logan", "lastName": "Shephard", "primaryWeightClass": 285, "secondaryWeightClass": undefined, "year": 4, "isRedshirt": false },
  { "firstName": "Brian", "lastName": "Shindel", "primaryWeightClass": 157, "secondaryWeightClass": undefined, "year": 3, "isRedshirt": false },
  { "firstName": "Blue", "lastName": "Stiffler", "primaryWeightClass": 133, "secondaryWeightClass": undefined, "year": 1, "isRedshirt": false },
  { "firstName": "Andrij", "lastName": "Szczesniuk", "primaryWeightClass": 125, "secondaryWeightClass": undefined, "year": 1, "isRedshirt": false },
  { "firstName": "Myles", "lastName": "Takats", "primaryWeightClass": 174, "secondaryWeightClass": undefined, "year": 3, "isRedshirt": false },
  { "firstName": "Creed", "lastName": "Thomas", "primaryWeightClass": 157, "secondaryWeightClass": 165, "year": 2, "isRedshirt": false },
  { "firstName": "Sean", "lastName": "Walker", "primaryWeightClass": 157, "secondaryWeightClass": undefined, "year": 2, "isRedshirt": false },
  { "firstName": "Cade", "lastName": "Wirnsberger", "primaryWeightClass": 157, "secondaryWeightClass": undefined, "year": 3, "isRedshirt": false }
];